services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Martin1982\LiveBroadcastEasyAdminBundle\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  Martin1982\LiveBroadcastEasyAdminBundle\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']
