name: Update monday

on:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  update-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress --no-suggest

      - name: Find and report outdated dependencies
        run: composer outdated --direct --strict
